### PR TITLE
Add option to save current file before running tests.

### PR DESCRIPTION
**Pull request by claytonrcarter**
Defaults to false (don't save), preserving current behavior.

### CODE REVIEW

**Comment by itmecho** [comment]
Good feature. This will clash with #10 when that gets merged in so might be coming back to it after that has happened

**Comment by claytonrcarter** [comment]
I can update this after the other is merged (or vice versa).  Also, should this be behind an option, or should saving the buffer just be default behavior?

**Comment by itmecho** [comment]
@claytonrcarter Merged in #10 so should be ready for you to fix

Cheers

**Comment by itmecho** [comment]
I think saving the current file would be a useful thing to configure. Maybe have it turned on by default but give people to option to disable it if it's not right for them

**Comment by claytonrcarter** [comment]
Done! I updated the default to 'true' so that files/buffers are saved by default before tests are run. It can be turned off via settings.

**Comment by itmecho** [comment]
Lovely! One last thing, can you pull in the latest changes on master? There should be a conflict with the config options as there is already a fifth option for font size!

**Comment by claytonrcarter** [comment]
Oops, sorry I missed that in all of the updates yesterday. It should be all set now. Thanks!

**Comment by claytonrcarter** [comment]
Any chance we could get another wave of PR reviews and maybe even another release?

**Pull request merged**
