### PR TITLE
Add feature to show test failures as notification.

### PR DESCRIPTION
**Pull request by claytonrcarter**
Defaults to false (show in output panel), which is current behavior.

### CODE REVIEW

**Comment by claytonrcarter** [comment]
Funny, I just looked back through the commit history and see that you had removed this feature in v1.2.  I find the failure notification helpful, because it pops up, tells you something's wrong, then goes away. I find that failures are usually something small that you just did, so it's pretty quick to home in on the issue to fix it.  For other cases, where the output requires more thought, it's easy to pull up the output panel.

Also, I realized that I named the option poorly.  It shouldn't be `errorsAsNotifications`, rather it should be `failuresAsNotifications`.  I'll correct that and update PR tomorrow morning.

Thanks!

**Comment by itmecho** [comment]
Thanks for the PR! Looks good, I'll wait for your commit and then merge it in

**Comment by claytonrcarter** [comment]
Done, thanks!

**Comment by claytonrcarter** [comment]
@Synapse791, anything I can do to help this along?

**Review by itmecho — APPROVED** [review]

**Comment by itmecho** [comment]
Sorry for the delay! Busy work schedule tends to get in the way =p

**Comment by claytonrcarter** [comment]
👍 Thanks! I'll try to update #9 later today.

**Pull request merged**
