### PR TITLE
Allow configuration of output view font size

### PR DESCRIPTION
**Pull request by thecrypticace**
See #11

### CODE REVIEW

**Comment by itmecho** [comment]
@thecrypticace Thanks for the pull request! I think this is going to wipe out some other changes that got pulled into the main branch. Could you update your branch with the changes?

**Comment by thecrypticace** [comment]
Yep. I'll do that in the next 30 minutes or so.

**Comment by thecrypticace** [comment]
Updated.

**Comment by itmecho** [comment]
Perfect! Thanks =]

**Pull request merged**
